//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FMsalon
{
    using System;
    using System.Collections.Generic;
    
    public partial class Service
    {
        public int serviceid { get; set; }
        public string serviceName { get; set; }
        public Nullable<decimal> servicePrice { get; set; }
        public string category_no { get; set; }
    
        public virtual Category Category { get; set; }
    }
}
